name: Prettier Check Workflow

on:                    
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prettier Check
        uses: rutajdash/prettier-cli-action@v1.0.2
        with:
          file_pattern: '**/*.{js,json,css,html}'
          config_path: ./.prettierrc.json
          ignore_path: ./.prettierignore
          prettier_version: latest
          fail_on_error: true

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"
