name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettier Check
        uses: creyD/prettier_action@v4.6
        with:
          # This part is also where you can pass other options, for example:
          dry: True
          prettier_options: --check **/*.{js,css,json,html}

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"
