name: Prettier Auto-Fix

# This action works with pushes only
on:
    push:
        branches:
            - main

jobs:
    prettier-fix:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Prettier and Commit Changes
              uses: creyD/prettier_action@v4.6
              with:
                  prettier_options: --write **/*.{js,css,json,html}
                  commit_message: 'style: auto-format code with Prettier'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
